import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  add,
  alertCircle,
  alertCircleOutline,
  barbell,
  calendarOutline,
  caretBack,
  caretForward,
  checkmarkCircle,
  checkmarkCircleOutline,
  chevronBack,
  chevronDown,
  chevronForward,
  chevronUp,
  close,
  closeCircleOutline,
  cloudyOutline,
  copy,
  flameOutline,
  flash,
  heartOutline,
  homeOutline,
  informationCircleOutline,
  notificationsOutline,
  pencil,
  personOutline,
  play,
  playCircleOutline,
  repeat,
  save,
  settings,
  settingsOutline,
  shareSocialOutline,
  statsChart,
  stop,
  timeOutline,
  trashBin,
  trophyOutline,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  standalone: true,
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  constructor() {
    addIcons({
      add,
      alertCircle,
      alertCircleOutline,
      barbell,
      calendarOutline,
      caretBack,
      caretForward,
      checkmarkCircleOutline,
      chevronBack,
      chevronDown,
      chevronForward,
      chevronUp,
      close,
      cloudyOutline,
      copy,
      flameOutline,
      flash,
      homeOutline,
      informationCircleOutline,
      pencil,
      personOutline,
      play,
      playCircleOutline,
      repeat,
      save,
      settings,
      stop,
      timeOutline,
      trashBin,
      trophyOutline,
      closeCircleOutline,
      notificationsOutline,
      statsChart,
      checkmarkCircle,
      settingsOutline,
      heartOutline,
      shareSocialOutline,
    });
  }
}
